
stages:
    - check
    - deploy
    
cache:
  paths:
    - vendor/

lint_php:
    stage: check
    image: docker.jbuncle.co.uk/jbuncle/php-docker
    script: phplint
    
deploy_nexus:
    stage: deploy
    image: docker.jbuncle.co.uk/jbuncle/php-docker
    script:
        - rm -rf nbproject
        - composer install --no-dev
        - composer nexus-push --url=https://nexus.jbuncle.co.uk/repository/composer-private/ --username=composer-publisher --password=$NEXUS_PASS  dev-master
    only:
        refs:
            - master
            
deploy_docker:
    stage: deploy
    image: "docker:latest"
    services:
      - docker:dind
    script: 
        - rm -rf nbproject
        - docker build -t docker.jbuncle.co.uk/jbuncle/php-autosemver.
        - docker push docker.jbuncle.co.uk/jbuncle/php-autosemver
    only:
        refs:
            - master